name: flutter_journal
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  cloud_firestore: 
  firebase_auth: 0.15.3

  firebase_storage:

  firebase_database: ^3.1.3

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  location: ^2.3.5
  image_picker: ^0.6.2
  share: ^0.6.3
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.5.1
  intl: ^0.16.0
  sentry: ^3.0.1
  firebase_analytics: ^5.0.11

flutter:
  uses-material-design: true

dependency_overrides:
  firebase_core: 0.4.4

  